on:
  push:
    branches: [ hw2 ]

jobs:
  test_my_hw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt-get update
          sudo pip install pylint
          sudo pip install flake8
          sudo pip install faker
      - name: Linters for main
        run: |
          flake8 --max-line-length=100 main.py
          pylint --disable=C0111 main.py
      - name: Linters for tests
        run: |
          flake8 --max-line-length=100 tests.py
      - name: Tests
        run: |
          python3 tests.py
