on:
  push:
    branches: [ hw1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt-get update
          sudo pip install pylint
          sudo pip install flake8
      - name: Linters
        run: |
          flake8 --max-line-length=100 main.py
          pylint --disable=C0111 main.py
