on:
  push:
    paths:
      - '05/**'
      - '.github/workflows/hw5_ci.yml'
jobs:
  test_my_hw:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./05
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install
        run: |
          sudo apt-get update
          sudo pip install pylint
          sudo pip install flake8
          sudo pip install black
          sudo pip install coverage
      - name: Linters for lru_cache
        run: |
          flake8 --max-line-length=100 lru_cache.py
          pylint --disable=C0111 lru_cache.py
          black --check --diff lru_cache.py
      - name: Linters for lru_tests
        run: |
          flake8 --max-line-length=100 lru_tests.py
          pylint --disable=C0111 lru_tests.py
          black --check --diff lru_tests.py

      - name: Linters for filter_file
        run: |
          flake8 --max-line-length=100 filter_file.py
          pylint --disable=C0111 filter_file.py
          black --check --diff filter_file.py
      - name: Linters for lru_tests
        run: |
          flake8 --max-line-length=100 filter_file_tests.py
          pylint --disable=C0111 filter_file_tests.py
          black --check --diff filter_file_tests.py
      - name: Tests for LRU Cache
        run: |
          python3 lru_tests.py
      - name: Tests for filter_file
        run: |
          python3 filter_file_tests.py
      - name: Coverage for LRU
        run: |
          coverage run lru_tests.py
          coverage report -m --omit="/usr/local/lib/*,/usr/lib/*"
          coverage html --omit="/usr/local/lib/*,/usr/lib/*"

      - name: Upload LRU coverage into artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LRU-coverage-report
          path: 05/htmlcov

      - name: Coverage for filter_file
        run: |
          coverage run filter_file_tests.py
          coverage report -m --omit="/usr/local/lib/*,/usr/lib/*"
          coverage html --omit="/usr/local/lib/*,/usr/lib/*"

      - name: Upload filter_file coverage into artifacts
        uses: actions/upload-artifact@v2
        with:
          name: filter_file-coverage-report
          path: 05/htmlcov
