on:
  push:
    paths:
      - '07/**'
      - '.github/workflows/hw7_ci.yml'
jobs:
  test_my_hw:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./07
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          sudo apt-get update
          pip install -r requirements.txt
      - name: Linters for python_matrix
        run: |
          pylint --disable=C0111 python_matrix.py
          flake8 --max-line-length=100 python_matrix.py
          black --check --diff python_matrix.py
      - name: Linters for c_matrix
        run: |
          pylint --disable=C0111,R0914 c_matrix.py
          flake8 --max-line-length=100 c_matrix.py
          black --check --diff c_matrix.py
      - name: Linters for compare
        run: |
          pylint --disable=C0111,C0209 compare.py
          flake8 --max-line-length=100 compare.py
          black --check --diff compare.py
      - name: Linters for tests
        run: |
          pylint --disable=C0111 tests.py
          flake8 --max-line-length=100 tests.py
          black --check --diff tests.py
      - name: Build dynamic library
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Tests
        run: |
          python3 tests.py
      - name: Coverage
        run: |
          coverage run tests.py
          coverage report -m --omit="/usr/local/lib/*,/usr/lib/*"
          coverage html --omit="/usr/local/lib/*,/usr/lib/*"
      - name: Upload coverage into artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: 07/htmlcov