on:
  push:
    paths:
      - '08/**'
      - '.github/workflows/hw8_ci.yml'
jobs:
  test_my_hw:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./08
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          sudo apt-get update
          pip install aiohttp
          pip install aiofiles
          pip install bs4
          pip install pylint
          pip install flake8
          pip install black
          pip install coverage
      - name: Linters for fetcher
        run: |
          flake8 --max-line-length=100 fetcher.py
          pylint --disable=C0111,E0401,W0703 fetcher.py
          black --check --diff fetcher.py
      - name: Linters for tests
        run: |
          flake8 --max-line-length=100 tests.py
          pylint --disable=C0111,E0401,W0703 tests.py
          black --check --diff tests.py
      - name: Tests
        run: |
          python3 tests.py
